### ISSUE TITLE
question can i use this for controlling my ac with esp32 that not have wifi units inside.

### ISSUE THREAD

**Issue by pbvdven** [unreality/FujiHeatPump#6]
I have 4 Fujitsu general aircon but only 2 of them have addon wifi units inside is it possible to fit the other 2 units with this project on esp32 and add then to home assistant? 

i have ac unit ASHG14KMCC.

Tanks

**Comment by unreality** [comment]
should be possible, you'll need to write the code to interact with home-assistant though

**Comment by pbvdven** [comment]
> should be possible, you'll need to write the code to interact with home-assistant though

Thanks

**Comment by pbvdven** [comment]
> should be possible, you'll need to write the code to interact with home-assistant though

My unit does not have an the optional communions kit needed for the 3 wire remote. i only have ir-remotecontrol but it has the connection for the wifi module but its 4 wires instead of 3 any idea how to make that work? ![image](https://user-images.githubusercontent.com/39600990/215269021-00e8665c-1f0b-40d9-8d50-68bd162313a1.jpeg)

The wifi controller is connected too the lower pcb not the communication pcb as in the picture.
![image](https://user-images.githubusercontent.com/39600990/215269639-15e6ca12-88aa-4bfe-bc24-3fdb33ba6dd6.jpeg)

**Comment by unreality** [comment]
Have a look at https://github.com/jaroslawprzybylowicz/fuji-iot 

It includes a PCB layout and BOM that hooks directly into the internal unit. I dont think it needs the communications PCB, but i could be mistaken.
